import type { Metadata } from "next";
import "./globals.css";
import { MantineProvider } from "@mantine/core";
import "@mantine/core/styles.css";
import NavBar from "@/components/modules/navBar/NavBar";
import Footer from "@/components/modules/footer/Footer";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
    >
      <body>
        <MantineProvider>
        {/* header */}
        <NavBar/>
        {/* main */}
        {children}
        {/* footer */}
        <Footer/>
        </MantineProvider>
        </body>
    </html>
  );
}
