import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/modules/navBar/NavBar";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
    >
      <body>
        {/* header */}
        <NavBar/>
        {/* main */}
        {children}
        {/* footer */}
        </body>
    </html>
  );
}
